---
title: "Fisher Water Quality Monitoring"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    self_contained: FALSE
    lib_dir: docs/site_libs
editor_options:
  chunk_output_type: console
params:
  dates:
    - "2020-01-24"
    - "2020-02-04"
  date_selected: "2020-02-04"
---

```{r setup, include=FALSE}
# cat(paste(dates, collapse='","'))
# c("2019-08-23","2019-09-01","2019-09-08","2019-09-18","2019-10-15","2019-11-01","2019-11-10","2019-12-07","2019-12-11","2019-12-17","2020-01-24","2020-02-04")
# params = list(
#   date          = c("2020-01-24", "2020-02-04"),
#   date_selected = "2020-01-24")
# params = list(
#   dates         = c("2019-08-23","2019-09-01","2019-09-08","2019-09-18","2019-10-15","2019-11-01","2019-11-10","2019-12-07","2019-12-11","2019-12-17","2020-01-24","2020-02-04"),
#   date_selected = "2020-02-04")
  #date_selected = "2020-08-23")

# load libraries
if (!require(librarian)) install.packages("librarian"); library(librarian)
shelf(
  flexdashboard, shiny, htmltools,
  fs, here, glue, digest,
  tibble, readr, dplyr, stringr, purrr, units,
  knitr,
  ggplot2,
  leaflet, sf, raster,
  marmap, mikkovihtakari/PlotSvalbard)
select = dplyr::select

dir_processed_csvs <- here("data/Raw Data")

processed_csvs <- tibble(
  path = list.files(dir_processed_csvs, "processed.*csv$", full.names = T),
  date = str_replace(path, ".*/processed_(.*)\\.csv", "\\1"))

# get dates ----
# date_dirs <- list.dirs(dir_data, recursive = F) %>% 
#     str_subset(".*/[0-9]{4}-[0-9]{2}-[0-9]{2}$")
```

Column {.tabset data-width=650}
-----------------------------------------------------------------------

```{r, eval=F}
# OLD SHINY, but keeping b/c
# TODO: stylize <select></select> below like prettier Shiny version
shiny::selectInput(
  "select_date", "Select date:", 
  choices = params$dates,
  selectize = F)
```


```{r}
tag_option_date2url <- function(date){
  
  # out_html <- knitr::current_input() %>% 
  #   basename() %>% 
  #   path_ext_set("html")
  
  # params <- list(
  #   dates         = c("2020-01-24", "2020-02-04"),
  #   date_selected = "2020-01-24")
  #   #date_selected = "2020-02-04")
  # #fname <- "index"
  # date = "2020-02-04"
  #date = "2020-01-24"
  
  date_index <- max(params$dates)
  
  date_url <- ifelse(
    date == date_index, 
    './index.html', 
    glue("./date_{date}.html"))
  #is_selected <- ifelse(out_html == basename(date_url), T, F)
  
  message(glue("date: {date}; params$date_selected: {params$date_selected}"))
  
  #option_args = list(value = date_url)
  is_selected <- NULL
  if(date == params$date_selected)
    is_selected <- NA
  
  tag(
    "option", 
    list(
      value    = date_url,
      selected = is_selected)) %>% 
    tagAppendChild(date)
}

tag(
  "select", 
  list(
    id = "sel_date", name = "", 
    onchange = "javascript:location.href = this.value;")) %>% 
  tagAppendChildren(
    map(params$dates, tag_option_date2url))
```

```{r}
get_transect <- function(){
#get_transect <- function(input = list(sel_date = processed_csvs$date[2])){
  # by date selected
  
  d  <- processed_csvs %>% 
    filter(date == as.Date(params$date_selected)) %>% 
    pull(path) %>% 
    read_csv()

  pts <- d  %>%
    group_by(csv, lon_dd, lat_dd) %>% 
    summarize(n = n()) %>% 
    ungroup() %>% 
    st_as_sf(
      coords = c("lon_dd", "lat_dd"), crs = 4326, remove = F)
  
  if (nrow(pts) > 1){
    ln  <- pts %>% st_coordinates() %>% st_linestring()
    ctr <- ln %>% st_centroid() %>% st_coordinates()
  } else {
    ln  <- NULL
    ctr <- pts %>% select(lon_dd, lat_dd) %>% st_drop_geometry() %>% as.numeric()
  }

  list(
    d   = d,
    pts = pts,
    ln  = ln,
    ctr = ctr)
}
```


### Map

```{r}
o <- get_transect()
  
map <- leaflet() %>% 
  addProviderTiles(providers$Esri.OceanBasemap) %>% 
  addMarkers(data = o$pts, popup = ~glue("{lon_dd}, {lat_dd}"))
if (!is.null(o$ln)){
  map <- map %>% 
    addPolylines(data = o$ln)
}
map %>% 
  addCircleMarkers(data = o$pts, stroke = F, radius = 5) %>% 
  setView(o$ctr[1], o$ctr[2], zoom = 10)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Temperature

```{r}
d <- o$d

# convert from degrees C to F
d <- d %>% 
  mutate(
    temp_c = set_units(temp_c, "deg_c"),
    temp_f = set_units(temp_c, "deg_f"))

# TODO add bottom_depth to points
contours = seq(
  min(d$temp_f), max(d$temp_f), length.out=5)[c(-1,-5)]

if (is.null(o$ln)){
  # TODO: fix plot for when no transect line, only single CTD cast
  d <- bind_rows(
    d,
    d %>% 
      mutate(
        lon_dd = lon_dd + 0.0001))
}

section_plot(
  d %>% data.frame(), 
  x    = "lon_dd"   , y    = "depth_ft"  , z    = "temp_f", 
  xlab = "Longitude", ylab = "Depth (ft)", zlab = "Temp (°F)",
  bottom = "bdepth_ft", sampling_indicator = "points",
  interpolate  = T, contour = contours, contour_color = "gray")
# TODO: customize https://github.com/MikkoVihtakari/PlotSvalbard/blob/master/R/section_plot.R
```

### Oxygen

```{r, eval=T}
d <- o$d
  
# read_csv("data.csv") %>% 
#   filter(
#     variable == "Temperature",
#     sensor_model == "Aqua TROLL 600 Vented")
contours = seq(
  min(d$o2_mgL), max(d$o2_mgL), length.out=5)[c(-1,-5)]


if (is.null(o$ln)){
  # TODO: fix plot for when no transect line, only single CTD cast
  d <- bind_rows(
    d,
    d %>% 
      mutate(lon_dd = lon_dd + 0.0001))}

section_plot(
  d %>% data.frame(), 
  x    = "lon_dd"   , y    = "depth_ft"  , z    = "o2_mgL", 
  xlab = "Longitude", ylab = "Depth (ft)", zlab = "Oxygen (mg/L)",
  bottom = "bdepth_ft", sampling_indicator = "points",
  interpolate  = T, contour = contours, contour_color = "gray")
```

### Salinity

```{r, eval=T}
d <- o$d
  
# read_csv("data.csv") %>% 
#   filter(
#     variable == "Temperature",
#     sensor_model == "Aqua TROLL 600 Vented")
contours = seq(
  min(d$salinity_psu), max(d$salinity_psu), length.out=5)[c(-1,-5)]


if (is.null(o$ln)){
  # TODO: fix plot for when no transect line, only single CTD cast
  d <- bind_rows(
    d,
    d %>% 
      mutate(lon_dd = lon_dd + 0.0001))}

section_plot(
  d %>% data.frame(), 
  x    = "lon_dd"   , y    = "depth_ft"  , z    = "salinity_psu", 
  xlab = "Longitude", ylab = "Depth (ft)", zlab = "Salinity (PSU)",
  bottom = "bdepth_ft", sampling_indicator = "points",
  interpolate  = T, contour = contours, contour_color = "gray")
```

### Chlorophyll

```{r, eval=T}
d <- o$d
  
# read_csv("data.csv") %>% 
#   filter(
#     variable == "Temperature",
#     sensor_model == "Aqua TROLL 600 Vented")
contours = seq(
  min(d$chl_mgL), max(d$chl_mgL), length.out=5)[c(-1,-5)]

if (is.null(o$ln)){
  # TODO: fix plot for when no transect line, only single CTD cast
  d <- bind_rows(
    d,
    d %>% 
      mutate(lon_dd = lon_dd + 0.0001))}

section_plot(
  d %>% data.frame(), 
  x    = "lon_dd"   , y    = "depth_ft"  , z    = "chl_mgL", 
  xlab = "Longitude", ylab = "Depth (ft)", zlab = "Chlorophyll (mg/L)",
  bottom = "bdepth_ft", sampling_indicator = "points",
  interpolate  = T, contour = contours, contour_color = "gray")
```
